# Example parameters for a minimal analysis run

dataset: cases
population_source: census_2020

time_window:
  start_date: "2024-01-01"
  end_date: "2024-01-31"

filters:
  exclude_missing: true
  min_case_count: 5

aggregation:
  group_by: county
  metric: incidence_rate
  per: 100000

